### ISSUE TITLE
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread

### ISSUE THREAD

**Issue by felipecrs** [OpenRGB-for-HA/openrgb_ha#39]
Also didn't find any report for this one.

```
2024-05-24 10:21:39.815 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.818 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

2024-05-24 10:21:39.819 WARNING (SyncWorker_33) [py.warnings] /usr/src/homeassistant/homeassistant/util/logging.py:110: RuntimeWarning: coroutine 'Entity.async_update_ha_state' was never awaited
  log_exception(format_err, *args)

2024-05-24 10:21:39.834 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.839 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

2024-05-24 10:21:39.862 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.866 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

2024-05-24 10:21:39.884 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.893 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

2024-05-24 10:21:39.910 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.915 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

2024-05-24 10:21:39.928 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True), please report it to the author of the 'openrgb' custom integration
2024-05-24 10:21:39.935 ERROR (SyncWorker_33) [homeassistant.util.logging] Exception in _update_callback when dispatching 'openrgb_update': ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 214, in send_header
    sent = self.sock.send(data, NOSIGNAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/__init__.py", line 223, in _get_updated_devices
    orgb.update()
  File "/usr/local/lib/python3.12/site-packages/openrgb/orgb.py", line 456, in update
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 187, in requestDeviceNum
    self.send_header(0, utils.PacketType.REQUEST_CONTROLLER_COUNT, 0)
  File "/usr/local/lib/python3.12/site-packages/openrgb/network.py", line 225, in send_header
    raise utils.OpenRGBDisconnected() from e
openrgb.utils.OpenRGBDisconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openrgb/light.py", line 240, in _update_callback
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
    self.hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'openrgb' calls async_create_task from a thread at custom_components/openrgb/light.py, line 240: self.async_schedule_update_ha_state(True). Please report it to the author of the 'openrgb' custom integration.

```

**Comment by maxi1134** [comment]
This is now a breaking error.
![image](https://github.com/user-attachments/assets/efcffee5-8014-4063-8872-00d0ae72804c)

**Comment by Bluscream** [comment]
Can someone PLEASE revive this? Or even better make it official?

**Comment by felipecrs** [comment]
I believe this has been solved by now. Please let me know otherwise.
